### ISSUE TITLE
pws doesn't work with ruby 2.2 because of cannot load such file -- digest/hmac (LoadError)

### ISSUE THREAD

**Issue by paneq** [janlelis/pws#17]
```/home/rupert/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- digest/hmac (LoadError)```

**Comment by janlelis** [comment]
Thanks, fixed in 1.0.6
