### ISSUE TITLE
Always Error "Key must be 32 bytes"

### ISSUE THREAD

**Issue by DiesDasJenes** [janlelis/pws#19]
Hi,
i am trying to create a new pws safe but every password i enter is being rejected with the error message "Key must be 32 bytes". I checked the passwords byte length with other password safes like KeePass. I am using ruby2.4 and the latest version of pws.  

Well after an afternoon of trying and searching i found this: https://github.com/attr-encrypted/encryptor/issues/26
It is an Error of the OpenSSL Library.

**Comment by janlelis** [comment]
Thanks for the bug report! I just released 1.0.7, which is compatible with Ruby 2.4.
