### ISSUE TITLE
Feature:  Disallowed chars

### ISSUE THREAD

**Issue by alex0112** [janlelis/pws#21]
Currently `pws gen` churns out a nice long random string of characters.  This is great, except when certain characters are disallowed in a password, such as quotes `'` `"`.

Feature request to disallow certain characters/specify only alphanumeric character sets when running `pws gen`.

**Comment by alex0112** [comment]
I'm willing to make this PR.  Just want to get confirmation that the maintainer would be open to merging it before I do.

**Comment by janlelis** [comment]
👍
